config/routes.rb
Routes::Application.routes.draw do

  devise_for :users , :skip => :registrations

  resources :users
  resources :routes do
    member do
      get 'reorder_morning_stops'
      get 'reorder_afternoon_stops'
    end
    resources :stops
  end

  resources :students do
    collection { post :import }
  end
  
  match '/mapstudents', :to => 'students#mapstudents', :via => [:get], :as => 'mapstudent'

  root :to => "students#index"

end

app/models/route.rb
class Route < ActiveRecord::Base
  has_many :stops
  belongs_to :morning_start_stop, :class_name => "Stop", :foreign_key => "morning_start_stop_id"
  belongs_to :morning_end_stop, :class_name => "Stop", :foreign_key => "morning_end_stop_id"
  belongs_to :afternoon_start_stop, :class_name => "Stop", :foreign_key => "afternoon_start_stop_id"
  belongs_to :afternoon_end_stop, :class_name => "Stop", :foreign_key => "afternoon_end_stop_id"
  
  accepts_nested_attributes_for :stops, :reject_if => :all_blank, :allow_destroy => true

  def student_count
  	total_count = 0
  	self.stops.each do | stop|
  	  total_count += stop.morning_students.count	
  	end
  	total_count 
  end


  def get_or_create_stop (address)
    route_id = self.id
      coords = Geocache.geocode(address)
      # while coords.nil?
      #   Rails.logger.debug ' sleeping for 2 sec to give google api a break.....'
      #   sleep 2
      #   coords = Geocoder.coordinates(address)
      # end
      stop = Stop.find_by(:latitude => coords[0], :longitude => coords[1], :route_id => route_id) || Stop.new

      stop.route_id = route_id
      
      stop.address = address
      stop.morning_arrive_time = Time.now
      stop.afternoon_arrive_time = Time.now
      stop.save
      
      return stop
  end


end

app/controllers/routes_controller.rb
class RoutesController < ApplicationController
  before_filter :authenticate_user!
  before_filter :is_admin?, except: [:index, :show]
  before_action :set_route, only: [:show, :edit, :update, :destroy]

  # GET /routes
  # GET /routes.json
  def index
    @routes = Route.all
  end

  def reorder_morning_stops

    @route_id = params[:id]
    @route = Route.find(@route_id)
    #make sure route has beginning and end stop ids
    @route.morning_start_stop_id = @route.morning_start_stop_id || @route.stops.first.id
    @route.morning_end_stop_id = @route.morning_end_stop_id || @route.stops.last.id
    @route.afternoon_start_stop_id = @route.afternoon_start_stop_id || @route.stops.last.id
    @route.afternoon_end_stop_id = @route.afternoon_end_stop_id || @route.stops.first.id
    @route.save

    @stops = Stop.joins(:morning_students).where('students.morning_stop_id = stops.id and stops.route_id = ? and stops.id != ? and stops.id != ? ', @route_id, @route.morning_start_stop_id , @route.morning_end_stop_id).distinct.order('morning_pickup_number asc').readonly(false)

    #add beginning and end stop
    @stops << @route.morning_end_stop
    @stops.unshift(@route.morning_start_stop)
    

    @xmlified_stops = xmlify_stops @stops
    @xmlified_stops = @xmlified_stops.gsub '&', 'and'
    @xml_addresses = ERB::Util.url_encode(@xmlified_stops)

    #send request to reorder stops
    response = RestClient.post  "http://www.mapquestapi.com/directions/v2/optimizedroute?key=sOgPH3Z8rohrbjFAAkz2FbryVKAKuoQ8&xml=#{@xml_addresses}", {:params => {"xml" => 's'}}

    response =  JSON.parse response  
    reordered_stops = response["route"]["locationSequence"]  
    
    reordered_stops.each_with_index do |stop, index|
      @stops[stop].morning_pickup_number = index
      @stops[stop].save
    end
  
    @start_time = @route.morning_start_time
    
    #get first stops arrive time from route info
    @stops[0].morning_arrive_time = @route.morning_start_time
    @stops[0].save
    
    #update stop arrive times based on results from mapquest
    response["route"]["legs"].each_with_index do |leg, index|
      @stops[index+1].morning_arrive_time = @stops[index].morning_arrive_time + leg["time"].seconds + 90.seconds # time for students to get in bus
      @stops[index+1].save
    end
    
    self.reorder_afternoon_stops
    
    redirect_to "/routes/#{@route_id}/"
  end
  
    def reorder_afternoon_stops
    @route_id = params[:id]
    @route = Route.find(@route_id)
    @stops = Stop.joins(:afternoon_students).where('students.afternoon_stop_id = stops.id and stops.route_id = ? and stops.id != ? and stops.id != ? ', @route_id, @route.afternoon_start_stop_id , @route.afternoon_start_stop_id).distinct.order('afternoon_pickup_number asc').readonly(false)

    #add beginning and end stop

    @stops << @route.afternoon_end_stop
    @stops.unshift(@route.afternoon_start_stop)
    
    @xmlified_stops = xmlify_stops @stops
    @xmlified_stops = @xmlified_stops.gsub '&', 'and'
    @xml_addresses = ERB::Util.url_encode(@xmlified_stops)
    
    #send request to reorder stops
    response = RestClient.post  "http://www.mapquestapi.com/directions/v2/optimizedroute?key=sOgPH3Z8rohrbjFAAkz2FbryVKAKuoQ8&xml=#{@xml_addresses}", {:params => {"xml" => 's'}}

    response =  JSON.parse response  
    reordered_stops = response["route"]["locationSequence"]  
    
    reordered_stops.each_with_index do |stop, index|
      @stops[stop].afternoon_pickup_number = index
      @stops[stop].save
    end
  
    @start_time = @route.afternoon_start_time
    
    #get first stops arrive time from route info
    @stops[0].afternoon_arrive_time = @route.afternoon_start_time
    @stops[0].save
    
    response["route"]["legs"].each_with_index do |leg, index|
      @stops[index+1].afternoon_arrive_time = @stops[index].afternoon_arrive_time + leg["time"].seconds + 90.seconds # time for students to get in bus
      @stops[index+1].save
    end
    
  end
  
  # GET /routes/1
  # GET /routes/1.json
  def show
    @route_id = params[:id]
    @return_directions = params[:return]
    @route = Route.find(@route_id)
    #@stops = Stop.where(:route_id => @route_id).order('morning_pickup_number asc') # .limit(8)

    @stops = Stop.joins(:morning_students).where('students.morning_stop_id = stops.id and stops.route_id = ?', @route_id).distinct.order('morning_pickup_number asc')
    #add beginning and end stop
    @stops << @route.morning_end_stop
    @stops.unshift(@route.morning_start_stop)

    @return_stops = Stop.joins(:afternoon_students).where('students.afternoon_stop_id = stops.id and stops.route_id = ?', @route_id).distinct.order('afternoon_pickup_number asc')
    #add beginning and end stop
    @return_stops << @route.afternoon_end_stop
    @return_stops.unshift(@route.afternoon_start_stop)

    @student_count = 0
    @addresses = []
    @return_addresses = []

    @ungeocoded_stops = false

    @stops.each do |stop| 
      if stop.latitude.nil? or stop.longitude.nil?
        @ungeocoded_stops = true
      end
      @addresses << stop.address 
      @student_count += stop.morning_students.count
    end

    @address_arr = []
    @addresses.each do |addr|
      @address_arr << '"' + addr + '"'
    end
    unless @return_directions.nil?
      @address_arr = @address_arr.reverse
    end
    @addresses = @address_arr.join(',')
    @addresses = @addresses.gsub '&', 'and'
    
    @hash = Gmaps4rails.build_markers(@stops) do |stop, marker|
      marker.lat stop.latitude
      marker.lng stop.longitude
      infobox= stop.address + "<br /> "
      stop.morning_students.each do |stud| infobox = infobox + " - " +  stud.first_name + " " + stud.last_name + "<br />" end
      marker.infowindow infobox
    end
    
  end

  
  # GET /routes/new
  def new
    @route = Route.new
    @stop = @route.stops.build

  end

  # GET /routes/1/edit
  def edit
    @route_id = params[:id]
    @route = Route.find(@route_id)
    @route_stops_select = @route.stops.map{|s| [s.address, s.id ]}
  end

  # POST /routes
  # POST /routes.json
  def create
    @route = Route.new(route_params)

    respond_to do |format|
      if @route.save
        format.html { redirect_to @route, notice: 'Route was successfully created.' }
        format.json { render action: 'show', status: :created, location: @route }
      else
        format.html { render action: 'new' }
        format.json { render json: @route.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /routes/1
  # PATCH/PUT /routes/1.json
  def update
    respond_to do |format|
      if @route.update(route_params)
        format.html { redirect_to @route, notice: 'Route was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @route.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /routes/1
  # DELETE /routes/1.json
  def destroy
    @route.destroy
    respond_to do |format|
      format.html { redirect_to routes_url }
      format.json { head :no_content }
    end
  end

  private
    # little xml builder for mapquest routes api
    def xmlify_stops stops

      xml = "<route><locations>"
      stops.each do |stop|
 
        xml += "<location><latLng><lat>" + stop.latitude.to_s + "</lat><lng>" + stop.longitude.to_s + "</lng></latLng></location>"   
      end
      xml += "</locations></route>"  
      return xml
    end
    # Use callbacks to share common setup or constraints between actions.
    def set_route
      @route = Route.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def route_params
      params.require(:route).permit(:name, :driver, :morning_start_time, :afternoon_start_time, :id, :morning_start_stop_id, :morning_end_stop_id, :afternoon_start_stop_id, :afternoon_end_stop_id, 
              stops_attributes:[:id, :route_id, :address, :morning_pickup_number, :afternoon_pickup_number, :morning_arrive_time, :afternoon_arrive_time, :_destroy
              ]
      )
    end
end

app/helpers/routes_helper.rb
module RoutesHelper
end

app/views/routes/_address_fields.html.erb
<%= f.simple_fields_for :stop_address do |address| %>
  <%= address.input :address_line_1 %>
  <%= address.input :address_line_2 %>
  <%= address.input :city %>
  <%= address.input :state %>
  <%= address.input :zip %>
<% end %>

app/views/routes/_form.html.erb
<%= simple_form_for @route, :html => { :class => 'form-horizontal' } do |f| %>
  <div id ="edit-route-fields">
    <%= f.input :name %>
    <%= f.input :driver %>
    <% unless @route.new_record? %>
      <%= f.input :morning_start_stop_id, :as => :select, :collection => @route_stops_select %>
      <%= f.input :morning_end_stop_id, :as => :select, :collection => @route_stops_select %> 
    <% end %>
    <%= f.input :morning_start_time %>
    <% unless @route.new_record? %>
      <%= f.input :afternoon_start_stop_id, :as => :select, :collection => @route_stops_select %>
      <%= f.input :afternoon_end_stop_id, :as => :select, :collection => @route_stops_select %>
    <% end %>
    <%= f.input :afternoon_start_time %>
  </div>    
  <br />
  <hr />
  <h3> Stops </h3>
  <div id="stops">

    <%= f.simple_fields_for :stops do |stop|%>
      <%= render 'stop_fields', :f => stop %>
    <% end %>
    <div class="links">
      <%= link_to_add_association 'add new stop', f, :stops, :class => 'btn orange' %>
    </div>      
  </div>    
  <div class="form-actions">
    <%= f.button :submit, :class => 'btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                routes_path, :class => 'btn' %>
  </div>
<% end %>

app/views/routes/_stop_fields.html.erb
<div class="nested-fields">
  <% unless @route.new_record? %>
    <%= f.input :morning_pickup_number %>
    <%= f.input :morning_arrive_time %>
    <%= f.input :afternoon_pickup_number %>
    <%= f.input :afternoon_arrive_time %>
    <%= f.input :address %>
  <% end %>
  <%= link_to_remove_association "remove stop", f , :class => 'btn' %>
</div>

app/views/routes/_stop_route_fields.html.erb
<h3> Morning Stops </h3>
<table class="table table-striped">
  <thead>
    <tr>
      <th>Stop #</th>
      <th>Stop Address</th>
      <th>Manual  Time</th>
      <th>Morning Pickup Time</th>
      <th>Actions</th>
    </tr>
  </thead>
  <tbody>
    <% stops.each do |stop| %>
      <% color = nil %>
      <!-- make sure stops with no geocoding are flagged-->
      <% if stop.latitude.nil? or stop.longitude.nil? %>
        <% color = 'red' %>
      <% end %>
      <tr>
        <td><%= stop.morning_pickup_number %></td>
        <td style="background-color:<%= color %>"><%= stop.address %> <span class="badge"><%= stop.morning_students.count %><%= content_tag :a, " students", :href => "#modal-pickup-#{stop.id}", :data => {:toggle => 'modal'} %></span></td>
        <td><%= stop.manual_morning_arrive_time.nil? ? nil : stop.manual_morning_arrive_time.strftime("%I:%M %p") %></td>
        <td><%= stop.morning_arrive_time.nil? ? nil : stop.morning_arrive_time.strftime("%I:%M %p") %></td>
        <td>
          <%= link_to 'View', route_stop_path(stop.route, stop), :class => 'btn btn-mini' %>
          <% if current_user.admin? %>
            <%= link_to 'Edit', edit_route_stop_path(stop.route, stop), :class => 'btn btn-mini' %>
          <% end %>
        </td>
      </tr>
      <% 
        content = ''
        stop.morning_students.each do |stud| 
          content = content + stud.first_name +  ' ' + stud.last_name + '  --  ' 
        end 

      %>
      <%= modal_dialog :id => "modal-pickup-#{stop.id}",
         :header => { :show_close => true, :dismiss => 'modal', :title => stop.address },
         :body   => content
      %> 
    <% end %>
  </tbody>
</table>
<hr />

<h3> Afternoon Stops </h3>
<table class="table table-striped">
  <thead>
    <tr>
      <th>Stop #</th>
      <th>Stop Address</th>
      <th>Manual  Time</th>
      <th>Afternoon Drop-off Time</th>
      <th>Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @return_stops.each do |stop| %>
      <tr>
        <td><%= stop.afternoon_pickup_number %></td>
        <td><%= stop.address %> <span class="badge"><%= stop.afternoon_students.count %><%= content_tag :a, " students", :href => "#modal-pickup-#{stop.id}", :data => {:toggle => 'modal'} %></span></td>
        <td><%= stop.manual_afternoon_arrive_time.nil? ? nil : stop.manual_afternoon_arrive_time.strftime("%I:%M %p") %></td>
        <td><%= stop.afternoon_arrive_time.nil? ? nil : stop.afternoon_arrive_time.strftime("%I:%M %p") %></td>
        <td>
          <%= link_to 'View', route_stop_path(stop.route, stop), :class => 'btn btn-mini' %>
          <% if current_user.admin? %>
            <%= link_to 'Edit', edit_route_stop_path(stop.route, stop), :class => 'btn btn-mini' %>
          <% end %>
        </td>
      </tr>
      <% 
        content = ''
        stop.afternoon_students.each do |stud| 
          content = content + stud.first_name +  ' ' + stud.last_name + '   --   ' 
        end 

      %>
      <%= modal_dialog :id => "modal-afternoon-#{stop.id}",
         :header => { :show_close => true, :dismiss => 'modal', :title => stop.address },
         :body   => content
      %>
    <% end %>
  </tbody>
</table>

app/views/routes/edit.html.erb
<%- model_class = Route -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/routes/index.html.erb
<%- model_class = Route -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:driver) %></th>
      <th># of students</th>
      <th><%= model_class.human_attribute_name(:morning_start_time) %></th>
      <th><%= model_class.human_attribute_name(:afternoon_start_time) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @routes.each do |route| %>
      <tr>
        <td><%= link_to route.id, route_path(route) %></td>
        <td><%= route.name %></td>
        <td><%= route.driver %></td>
        <td><%= route.student_count %></td>
        <td><%= route.morning_start_time.strftime("%I:%M %p") %></td>
        <td><%= route.afternoon_start_time.strftime("%I:%M %p") %></td>
        <td>
          <% if current_user.admin? %>
            <%= link_to t('.edit', :default => t("helpers.links.edit")),
                        edit_route_path(route), :class => 'btn btn-mini' %>
            <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                        route_path(route),
                        :method => :delete,
                        :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                        :class => 'btn btn-mini btn-danger' %>
          <% else %>   
            <%= link_to t('.show', :default => t("helpers.links.show")),
                        route_path(route), :class => 'btn btn-mini' %>           
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
<% if current_user.admin? %>
  <%= link_to t('.new', :default => t("helpers.links.new")),
              new_route_path,
              :class => 'btn btn-primary' %>
<% end %>

app/views/routes/new.html.erb
<%- model_class = Route -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/routes/show.html (copy).erb
<%- model_class = Route -%>
<div class="page-header">
  <h4><%= "Route (#{@student_count} students)" %></h4>

    <script type="text/javascript"
      src="https://maps.googleapis.com/maps/api/js?sensor=false">
    </script>

  
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @route.name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:driver) %>:</strong></dt>
  <dd><%= @route.driver %></dd>
  <dt><strong><%= model_class.human_attribute_name(:morning_start_time) %>:</strong></dt>
  <dd><%= @route.morning_start_time.strftime("%I:%M %p") %></dd>
  <dt><strong><%= model_class.human_attribute_name(:afternoon_start_time) %>:</strong></dt>
  <dd><%= @route.afternoon_start_time.strftime("%I:%M %p") %></dd>
</dl>

<div id="start"><%= @route.morning_start_stop.address %></div>
<div id="end"><%= @route.morning_end_stop.address %></div>
    
<div class ="optimize">
<%= link_to "Optimize Route",
            reorder_morning_stops_route_path(@route),
            :data => { :confirm => 'Are you sure?' },
            :class => 'btn btn-danger' %>
</div>              
<div style='width: 1200px;margin:auto;'>
  <div id="map" style='width: 1200px; height: 600px;'></div>
</div>

<%= render 'stop_route_fields', :stops => @stops %>

<div id="directions_panel"></div>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              routes_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_route_path(@route), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              route_path(@route),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>
<script>
var directionsDisplay;
var directionsService = new google.maps.DirectionsService();
var map;

function initialize() {
  directionsDisplay = new google.maps.DirectionsRenderer();
  var chicago = new google.maps.LatLng(41.850033, -87.6500523);
  var mapOptions = {
    zoom: 6,
    center: chicago
  }
  map = new google.maps.Map(document.getElementById("map"), mapOptions);
  directionsDisplay.setMap(map);
  calcRoute();  
}
function calcRoute2() {
  var start = document.getElementById("end").innerHTML;
  var end = document.getElementById("start").innerHTML;
  var waypts = [];

  var checkboxArray = ['555 e main st columbus, oh', '45 N high st columbus, oh', '1254 morse rd columbus, oh']; // careful
  for (var i = 0; i < checkboxArray.length; i++) {

      waypts.push({
          location:checkboxArray[i],
          stopover:true
      });
    
  }

  var request = {
      origin: start,
      destination: end,
      waypoints: waypts,
      optimizeWaypoints: false,
      travelMode: google.maps.TravelMode.DRIVING
  };
  directionsService.route(request, function(response, status) {
    if (status == google.maps.DirectionsStatus.OK) {
      directionsDisplay.setDirections(response);
      var route = response.routes[0];
      var summaryPanel = document.getElementById("directions_panel");
      summaryPanel.innerHTML = "";
      // For each route, display summary information.
      for (var i = 0; i < route.legs.length; i++) {
        var routeSegment = i+1;
        summaryPanel.innerHTML += "<b>Route Segment: " + routeSegment + "</b><br />";
        summaryPanel.innerHTML += route.legs[i].start_address + " to ";
        summaryPanel.innerHTML += route.legs[i].end_address + "<br />";
        summaryPanel.innerHTML += route.legs[i].distance.text + "<br /><br />";
      }
    }
  });
}
function calcRoute() {
  var start = document.getElementById("start").innerHTML;
  var end = document.getElementById("end").innerHTML;
  var waypts = [];

  var checkboxArray = [<%= raw @addresses %>]; // careful
  for (var i = 0; i < checkboxArray.length; i++) {

      waypts.push({
          location:checkboxArray[i],
          stopover:true
      });
    
  }

  var request = {
      origin: start,
      destination: end,
      waypoints: waypts,
      optimizeWaypoints: false,
      travelMode: google.maps.TravelMode.DRIVING
  };
  directionsService.route(request, function(response, status) {
    if (status == google.maps.DirectionsStatus.OK) {
      directionsDisplay.setDirections(response);
      var route = response.routes[0];
      var summaryPanel = document.getElementById("directions_panel");
      summaryPanel.innerHTML = "";
      // For each route, display summary information.
      for (var i = 0; i < route.legs.length; i++) {
        var routeSegment = i+1;
        summaryPanel.innerHTML += "<b>Route Segment: " + routeSegment + "</b><br />";
        summaryPanel.innerHTML += route.legs[i].start_address + " to ";
        summaryPanel.innerHTML += route.legs[i].end_address + "<br />";
        summaryPanel.innerHTML += route.legs[i].distance.text + "<br /><br />";
      }
    }
  });
}
            google.maps.event.addDomListener(window, 'load', initialize);
</script>