config/routes.rb
Routes::Application.routes.draw do

  devise_for :users , :skip => :registrations

  resources :users
  resources :routes do
    member do
      get 'reorder_morning_stops'
      get 'reorder_afternoon_stops'
    end
    resources :stops
  end

  resources :students do
    collection { post :import }
  end
  
  match '/mapstudents', :to => 'students#mapstudents', :via => [:get], :as => 'mapstudent'

  root :to => "students#index"

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Zenith - Routes" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->


    <link href="/assets/application.css?body=1" media="all" rel="stylesheet" />
    <link href="/assets/twitter-bootstrap-static/bootstrap.css?body=1" media="all" rel="stylesheet" />
    <link href="/assets/twitter-bootstrap-static/fontawesome.css?body=1" media="all" rel="stylesheet" />
    <link href="/assets/bootstrap_and_overrides.css?body=1" media="all" rel="stylesheet" />
    <link href="/assets/routes.css?body=1" media="all" rel="stylesheet" />
    <link href="/assets/scaffolds.css?body=1" media="all" rel="stylesheet" />
    <link href="/assets/stops.css?body=1" media="all" rel="stylesheet" />
    <link href="/assets/students.css?body=1" media="all" rel="stylesheet" />

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>

  </head>
  <body>

    <div class="navbar navbar-fluid-top">
      <div class="navbar-inner">
        <div class="container-fluid">
          <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <%= image_tag "ZAE_1.jpg", :class => 'zae-logo' %>
          <a class="brand" href="#">ZENITH ACADEMY EAST</a>
        <% if user_signed_in? %>
          <div id="welcome_message"><h4>Welcome <%= current_user.username %> !</h4></div>
        <% end %>
                <div class="container-fluid nav-collapse">
            <ul class="nav">
              <% if user_signed_in? %>
                <li>
                <%= link_to('Logout', destroy_user_session_path, :method => :delete) %>        
                </li>
              <% else %>
                <li>
                <%= link_to('Login', new_user_session_path)  %>  
                </li>
              <% end %>
              <li><%= link_to "Students", students_path  %></li>
              <li><%= link_to "Routes", routes_path  %></li>
              <li><%= link_to "Map Students", mapstudent_path  %></li>
              <% if user_signed_in? && current_user.admin? %>
                <li><%= link_to "Manage Users", users_path  %></li>
              <% end %>
            </ul>
        </div><!--/.nav-collapse -->
        </div>

      </div>
    </div>

    <div class="container-fluid">
      <div class="row-fluid">
        <div class="span2">
          <div class="well sidebar-nav">
            <ul class="nav nav-list">
              <li class="nav-header">Menu</li>
              <% if user_signed_in? %>
                <li>
                <%= link_to('Logout', destroy_user_session_path, :method => :delete) %>        
                </li>
              <% else %>
                <li>
                <%= link_to('Login', new_user_session_path)  %>  
                </li>
              <% end %>
              <li><%= link_to "Students", students_path  %></li>
              <li><%= link_to "Routes", routes_path  %></li>
              <li><%= link_to "Map Students", mapstudent_path  %></li>
              <% if user_signed_in? && current_user.admin? %>
                <li><%= link_to "Manage Users", users_path  %></li>
              <% end %>
            </ul>
          </div><!--/.well -->
        </div><!--/span-->
        <div class="span10">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
      </div><!--/row-->

      <footer>
        <p>&copy; Company 2014</p>
      </footer>

    </div> <!-- /container -->

  </body>
</html>